### ISSUE TITLE
Illegal/unsupported syntax

### ISSUE THREAD

**Issue by sonicsmooth** [technomancy/slamhound#98]
Clojure 1.8.0, Java 1.8.0_144, slamhound 1.5.5
Windows 10, x64, with git bash inside a ConsoleZ

My profiles.clj includes:

    {:user {:dependencies [[org.clojure/clojure "1.8.0"]
                           [slamhound "1.5.5"]]
            :aliases {"slamhound" ["run" "-m" "slam.hound"]}}}

When I change to myproject/src/myproject directory and directly type `lein slamound core.clj`, I get the same error as was filed in 2014:

    Exception in thread "main" java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 16
        ^C:\dev\clojure\jfxutils\target\classes
                ^, compiling:(search.clj:171:8)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3651)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3651)
        at clojure.lang.Compiler$DefExpr.eval(Compiler.java:451)
    (... lots more ...)

I see the issue was closed after a fix, but apparently the version I got yesterday (October 2017) did not work.

Is there a workaround/fix?

thank you :)

**Comment by dbyrne** [comment]
Looks like the fix for this bug was never published, which makes Slamhound unusable on Windows.
